channels:
  - conda-forge
  - defaults
dependencies:
  - colour-science
  - ipywidgets
  - matplotlib
  - pandas
  # Jupyter
  - jupyterlab=2
  - nodejs=11
  - nbconvert=5.5
  - widgetsnbextension=3.5
