#!/bin/bash

poetry install
poetry run python -c "import imageio;imageio.plugins.freeimage.download()"

# Install JupyterLab extensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib
